export const AUTHORIZED = "AUTHORIZED";
export const FAIL = "FAIL";
export const REDIRECT_TO_CONFIRM = "REDIRECT_TO_CONFIRM";
export const WALLET_INFORMATION = "WALLET_INFORMATION";
export const ALERT_MESSENGER = "ALERT_MESSENGER";
export const BOOK_PURCHASE = "BOOK_PURCHASE";
